services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: vzkz-server
    env_file:
      - .env
    volumes:
      - ${VAULT_LOCATION}:/vault
      - ${DOCKER_CONFIG_FOLDER}:/var/syncthing
    ports:
      - '8384:8384'
    network_mode: bridge
    restart: unless-stopped

